// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class ClockRecord
{
    /// <summary>
    /// 打卡記錄唯一識別碼 (GUID)
    /// </summary>
    public Guid ID { get; set; }

    /// <summary>
    /// 關聯 Employee.ID 的外鍵 (員工識別碼)
    /// </summary>
    public Guid EmployeeID { get; set; }

    /// <summary>
    /// 打卡發生的日期與時間，精確到毫秒
    /// </summary>
    public DateTime ClockDateTime { get; set; }

    /// <summary>
    /// 打卡類型，如 In / Out / Break / Overtime 等
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// 打卡地點或裝置標識 (可選，若沒有可為 NULL)
    /// </summary>
    public string Location { get; set; }

    /// <summary>
    /// 此筆紀錄的建立時間 (UTC 時間)
    /// </summary>
    public DateTime CreatedDT { get; set; }

    public virtual Employee Employee { get; set; }
}