// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class Employee
{
    /// <summary>
    /// 員工唯一識別碼（GUID），主鍵，系統自動產生。
    /// </summary>
    public Guid ID { get; set; }

    /// <summary>
    /// 員工編號（例如：EMP001），公司內部代碼，不可重複。
    /// </summary>
    public string No { get; set; }

    /// <summary>
    /// 員工的中文或英文姓名。
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 員工的電子郵件地址，用於通知與聯絡。
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 員工的行動電話號碼，用於聯絡用途。
    /// </summary>
    public string Mobile { get; set; }

    /// <summary>
    /// 員工正式入職公司的日期。
    /// </summary>
    public DateOnly HireDate { get; set; }

    /// <summary>
    /// 大頭照對應的 FileStorage 資料表主鍵 ID。
    /// </summary>
    public Guid? Photo { get; set; }

    /// <summary>
    /// 人臉辨識特徵檔案對應的 FileStorage 資料表主鍵 ID。
    /// </summary>
    public Guid? FaceFeature { get; set; }

    /// <summary>
    /// 建立時間（系統自動記錄）。
    /// </summary>
    public DateTime CreatedDT { get; set; }

    /// <summary>
    /// 最後一次修改此筆資料的時間戳記，可為 NULL。
    /// </summary>
    public DateTime? ModifiedDT { get; set; }

    public virtual FileStorage FaceFeatureNavigation { get; set; }

    public virtual FileStorage PhotoNavigation { get; set; }
}