// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class FileStorage
{
    public Guid ID { get; set; }

    public string Type { get; set; }

    public string FileName { get; set; }

    public int FileSize { get; set; }

    public string Path { get; set; }

    public Guid? CreatedUserID { get; set; }

    public DateTime CreatedDT { get; set; }
}