// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class User
{
    public Guid ID { get; set; }

    public string Account { get; set; }

    public string AccountNormalize { get; set; }

    public string Email { get; set; }

    public string EmailNormalize { get; set; }

    public string PasswordHash { get; set; }

    public string Name { get; set; }

    public string Mobile { get; set; }

    public DateOnly? Birthday { get; set; }

    public string Address { get; set; }

    public DateTime? LockoutEnd { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public DateTime CreatedDT { get; set; }

    public DateTime? ModifiedDT { get; set; }
}